title: Interesting Things
author: Grant Emsley
description: >
  This is a brain dump of things I learn at work and home, various projects I've worked on, etc. It's mostly for my own reference, but if other people find it interesting or helpful, great!
baseurl: ""
timezone: America/Toronto
show_excerpts: false
permalink: /:categories/:title
rss: rss
minima:
  date_format: "%Y-%m-%d"

# Social
github_username: grantemsley
google_analytics: UA-116270908-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  
defaults:
  - scope:
      path: _posts
    values:
      layout: post
